spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emartplus
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    jwt:
      secret: your-secret-key
      expiration: 86400000  # 24 hours
      refresh-token:
        expiration: 604800000  # 7 days

server:
  port: 8080

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION:us-east-1}
    stack:
      auto: false 